### ISSUE TITLE
Bug and feature requests

### ISSUE THREAD

**Issue by ConsciousCode** [ShadowOne333/The-Legend-of-Zelda-Redux#1]
During gameplay I noticed that for the colored dungeons mod, the palette isn't swapped back after coming up from an underground area (which sets the palette to grey).

Some ideas for features:
* Burnable bush sprite (considering the hoops you had to go through for cracked walls I know this is a big ask)
* Make peahats vulnerable to arrows or stunnable by boomerang (as-is they're invulnerable unless resting which makes fighting them obnoxious)
* Close caves whose NPCs leave
* Keep the level 7 pond drained and enable flute for that screen (only a minor annoyance)
* Optional mod to disable "low health" sound effect

Overall these mods are a lifesaver, this is my first time playing through to the end and I don't think I would've gotten this far without these QoL improvements. Great work!

**Comment by ShadowOne333** [comment]
7c5e950f4bb724828505455b4841d8f25f8b0853

**Comment by ShadowOne333** [comment]
Commit 7c5e950f4bb724828505455b4841d8f25f8b0853 should fix the issues with the Recoloured Dungeons optional patch.

Could you try that one and let me know if it's fixed?
I also added additional code to make the sprite objects have the same palette as the dungeon (like in original Zelda) and also modified the palette for Dark rooms so the outlines match the recoloured dungeon.

Only thing I haven't changed is the fade-out / fade-in colours for each dungeon, as that would be really long to do for such a short and almost meaningless thing.

Let me know if this worked so I can close the issue.

As for your other requests, I do want to add burnable trees, but unless I figure out a way to make more room for sprites, I don't see it happening (unless MMC3/MMC5 becomes a thing with bankswapping).

Disabling the Low Health SFX should be a handful of bytes change, I'll see what I can do, but atm the focus should be on the issue at hand, which is the Recoloured Dungeons patch.

EDIT:
Added the "Remove Low Health Beep" optional patch.
Please check that one out as well.

**Comment by ShadowOne333** [comment]
Closing due to the issue being fixed alongside the inclusion of the Beep removal optional patch
