### ISSUE TITLE
Unexplored dungeon rooms appearing on HUD automap

### ISSUE THREAD

**Issue by fridaykitty** [ShadowOne333/The-Legend-of-Zelda-Redux#15]
After fully exploring and collecting maps in earlier dungeons, unseen rooms in later dungeons are shown as explored in the HUD automap. The map on the start menu correctly shows these rooms as unexplored.
![Zelda1_Redux_000](https://github.com/ShadowOne333/The-Legend-of-Zelda-Redux/assets/87046568/455a0993-93cd-4ca7-9843-dac7295855fe)
Redux v3.3.1 via Mesen emulator

**Comment by ruffe972** [comment]
I have this problem too with Dungeon 9

**Comment by ShadowOne333** [comment]
This is a known issue with the Dungeon Automap by tacoschip, he was aware of the issue but I haven't heard from him on a possible solution.

Can you guys confirm if this is actually only happening in Dungeon 9, or does it also happen in Dungeon 8 or others?

**Comment by ericune** [comment]
I can confirm this happened to me on dungeons 7, 8 and 9 on the first quest, and I think the same happened to me on the 2nd quest, but not 100% sure.
I was playing v3.3.1 with no Optional Patches.

**Comment by ghost** [comment]
Dungeon 9 is reading wrong automap data. PR sent.

**Comment by ShadowOne333** [comment]
Thanks @vailkyte.
I'll close this issue and continue the discussion for this bug in the PR #16.
