### ISSUE TITLE
Blank Title Screen

### ISSUE THREAD

**Issue by RintaDev5792** [ShadowOne333/The-Legend-of-Zelda-Redux#18]
When I load into the game in FCEUX 2.6.5 and on my flash cartridge, it only displays a blank tan screen and no buttons do anything. This hack looks amazing and it's a shame it isn't working :/

**Comment by ShadowOne333** [comment]
Make sure you have the right base ROM with the correct checksum and that you're also patching the game correctly.
I just tested the romhack with FCEUX 2.6.5 and it's working fine on my end:
![image](https://github.com/ShadowOne333/The-Legend-of-Zelda-Redux/assets/13888698/8ccc2d85-f653-40a1-b7b1-e8b35f958460)

For reference, my MD5 checksum for a Redux patched ROM (without any optional patch), should be 06b75f8bdb922dc294aeefb4b2eec5c4

**Comment by RintaDev5792** [comment]
I have no clue what that means sorry - how do I check I have the right rom and all? I'm new to this lol

**Comment by RintaDev5792** [comment]
Oh wait I found the forum post abt it I was using PRG1 I think that's the issue

**Comment by ShadowOne333** [comment]
Go to the online patcher here:
https://www.romhacking.net/patch/index.php?file=hacks/5752&patch_name=The+Legend+of+Zelda+Redux++hack+v3.3.2&crc=D7AE93DF

Browse your ROM and upload it there, it will automatically check if it is the right version, and if not, then look for one that checks out.

**Comment by RintaDev5792** [comment]
Ok I got the PRG0 one and it works perfectly! TYSM!

**Comment by ShadowOne333** [comment]
Awesome! Glad you got it working, enjoy the hack!

**Comment by RintaDev5792** [comment]
Played through the first couple dungeons and this is definitely one of my fav hacks of any time of any game, and possibly *the* best way to play the original Zelda! Thank you for making this!
