### ISSUE TITLE
[Optional Patch Request] Increase drop rate of all enemies

### ISSUE THREAD

**Issue by louisdefromont** [ShadowOne333/The-Legend-of-Zelda-Redux#7]
I think it would be nice to have a patch that increases (doubles) the drop rates of all enemies so that grinding for rupees/hearts is less tedious.

**Comment by ShadowOne333** [comment]
It might be possible to modify the probabilities, but I'm not 100% sure where the data for that is stored.
Do you know how to Hex edit a ROM?

Simply open your Zelda 1 ROM in an Hex editor, like HxD, and then press Ctrl+G, and type "1304E" (without the quotation marks. Once you do that, you should see the following:
`50 98 68 68`

Apparently that's the drop probability.
If you can, change those 4 values to something like `A0 A0 A0 A0`. If my assumption is correct, then the probabilities for all drops should increase. 
Let me know how it went.
