### ISSUE TITLE
[Bug] "Full Health After Death" patch freezes when entering cave

### ISSUE THREAD

**Issue by louisdefromont** [ShadowOne333/The-Legend-of-Zelda-Redux#8]
I applied the "Full Health After Death" patch (MMC5) to a working Zelda 1 ROM that had been patched with Redux. I'm able to start the game and go between screens, but entering any cave will just freeze the game on this frame:
![image](https://user-images.githubusercontent.com/88596228/158042914-5108ccea-0717-412f-ac8f-12c86a004b08.png)
The Redux patch alone works correctly, as well as when patched with other optional patches.

FCEUX v2.6.2
Zelda1ROM.nes SHA1 Sum: `dab79c84934f9aa5db4e7dad390e5d0c12443fa2`
ReduxPatchOnly.nes SHA1 SUM: `1cb1aacfc28eb98b1b6f67db233ae7c44f3e6a13`
ReduxPlusFullHealthAfterDeathPatch.nes SHA1 SUM: `5a572cf39134cede24f2f0c07aa6d4021dfd3c8b`

**Comment by ShadowOne333** [comment]
Fixed in commit [a3a068e](https://github.com/ShadowOne333/The-Legend-of-Zelda-Redux/commit/a3a068e41f11eb24929ca022a56bfa7f253eaba9)
