### ISSUE TITLE
[optional patch request] un-fix level one door bug

### ISSUE THREAD

**Issue by jason-oliveira** [ShadowOne333/The-Legend-of-Zelda-Redux#9]
Hi, In Zelda Redux, it's impossible to do the "door unlocking without using key" trick, one that was mentioned in the original Zelda instruction booklet, because the "bug" behind it was "fixed".

This Issue is to request restoration of broken game functionality, so completionists can earn all the [retroachievements in Zelda](https://retroachievements.org/achievement/33399) with this hack.

**Comment by ShadowOne333** [comment]
Could you test if the following patch does restore that door unlocking glitch on Dungeon 1?
If it does, I will add this as an optional patch.

[Restore Door Glitch.zip](https://github.com/ShadowOne333/The-Legend-of-Zelda-Redux/files/8871551/Restore.Door.Glitch.zip)

**Comment by jason-oliveira** [comment]
It works perfectly. Thank you so much.

**Comment by ShadowOne333** [comment]
Awesome, the optional patch should now be available in this repo and in the RHDN page as well.
Thanks for testing.
